---
title: "R Notebook"
output: html_notebook
---

```{r}
source("R/common.R", local = knitr::knit_global())
library(ggplot2)
library(ggalluvial)
```

```{r}
insect_plant_cluster_json = read_input_json(INSECT_PLANT_CLUSTERS)
bird_cluster_json = read_input_json(BIRD_CLUSTERS)

row_to_df = function(x) {
  tibble(
    cluster_id = as.integer(x$cluster_id),
    cluster_name = x$cluster_name,
    cluster_description = x$cluster_description,
    habitat_description_from_photos = x$habitat_description_from_photos,
    representative_plot_image = x$representative_plot_image
  )
}

bird_clusters = map_dfr(bird_cluster_json, row_to_df) %>% dplyr::select(cluster_id, cluster_name)
insect_plant_clusters = map_dfr(insect_plant_cluster_json, row_to_df) %>% dplyr::select(cluster_id, cluster_name)
insect_plant_clusters
```



```{r}
plots_in_cluster = function(cluster_json, cluster_id) {
  idx = which(sapply(cluster_json, function(x) x$cluster_id) == cluster_id)
  if (length(idx) == 0) return(NULL)
  
  df = data.frame(plot_id = cluster_json[[idx]]['plots'])
  df$cluster_id = cluster_id
  df
}

plots_in_cluster_insect_plants = function(cluster_id) plots_in_cluster(insect_plant_cluster_json, cluster_id)
plots_in_cluster_birds = function(cluster_id) plots_in_cluster(bird_cluster_json, cluster_id)

plots_in_cluster_insect_plants(8)
```


```{r}
insect_plants_plots = map_dfr(0:9, plots_in_cluster_insect_plants) %>% left_join(insect_plant_clusters, by = 'cluster_id') %>% rename('plot_id' = plots)
insect_plants_plots
```

```{r}
bird_plots = map_dfr(0:9, plots_in_cluster_birds) %>% left_join(bird_clusters, by = 'cluster_id') %>% rename('plot_id' = plots)
bird_plots
```

Order clusters by NDVI
```{r}
bird_clusters = bird_plots %>% 
  left_join(read_input_csv(BIRD_PREDICTORS) %>% to_ndvi()) %>% 
  group_by(cluster_name) %>% 
  summarise(avg_ndvi = mean(ndvi)) %>%
  left_join(bird_clusters) %>%
  arrange(avg_ndvi)
bird_clusters
```

```{r}
insect_plant_clusters = insect_plants_plots %>% 
  left_join(read_input_csv(INSECT_PLANT_PREDICTORS) %>% to_ndvi()) %>% 
  group_by(cluster_name) %>% 
  summarise(avg_ndvi = mean(ndvi)) %>%
  left_join(insect_plant_clusters) %>%
  arrange(avg_ndvi)
insect_plant_clusters
```

```{r}
plots = insect_plants_plots %>% left_join(insect_plant_clusters) %>% rename('insect_plants_cluster_name' = cluster_name, 'insect_plants_ndvi' = avg_ndvi) %>% 
  dplyr::select(plot_id, insect_plants_cluster_name, insect_plants_ndvi) %>% 
  left_join(bird_plots %>% left_join(bird_clusters) %>% rename('birds_cluster_name' = cluster_name, 'birds_ndvi' = avg_ndvi) %>% dplyr::select(plot_id, birds_cluster_name, birds_ndvi)) %>%
  arrange(insect_plants_ndvi, birds_ndvi) %>%
  dplyr::select(plot_id, insect_plants_cluster_name, birds_cluster_name)
plots
```


```{r}
# Long format for ggalluvial
plots_long =
  plots %>%
  pivot_longer(
    cols = c(insect_plants_cluster_name, birds_cluster_name),
    names_to = "scale",
    values_to = "cluster"
  ) %>%
  mutate(
    # order left–right
    scale = factor(scale,
                   levels = c("insect_plants_cluster_name", "birds_cluster_name"),
                   labels = c("20 x 20 m Cluster", "120 x 120 m Cluster")),
    # make sure cluster order is consistent and not alphabetical chaos
    cluster = factor(cluster)
  )

ggplot(
  plots_long,
  aes(
    x = scale,
    stratum = cluster,
    alluvium = plot_id,   # one flow per plot
    y = 1
  )
) +
  geom_flow(
    stat = "alluvium",
    lode.guidance = "forward",
    alpha = 0.3
  ) +
  geom_stratum(width = 0.4) +
  geom_text(
    stat = "stratum",
    aes(label = cluster),
    size = 3
  ) +
  scale_x_discrete(expand = c(0.2, 0.2)) +
  labs(
    x = NULL,
    y = "Number of plots",
    title = "Movement of plots between clusterings"
  ) +
  theme_minimal()

```

```{r}
# Count how many plots move from each cluster pair
flows =
  plots %>%
    count(insect_plants_cluster_name, birds_cluster_name, name = "n") %>%
    left_join(insect_plant_clusters %>% dplyr::select(cluster_name, avg_ndvi) %>% rename('insect_ndvi' = avg_ndvi, 'insect_plants_cluster_name' = cluster_name)) %>%
    left_join(bird_clusters %>% dplyr::select(cluster_name, avg_ndvi) %>% rename('bird_ndvi' = avg_ndvi, 'birds_cluster_name' = cluster_name)) %>%
    arrange(insect_ndvi, bird_ndvi) %>%
    mutate(
      # left axis ordered by insect_ndvi
      insect_plants_cluster_name =
        fct_reorder(insect_plants_cluster_name, insect_ndvi),

      # right axis ordered by bird_ndvi
      birds_cluster_name =
        fct_reorder(birds_cluster_name, bird_ndvi)
    )


ggplot(flows,
       aes(
         axis1 = insect_plants_cluster_name,
         axis2 = birds_cluster_name,
         y = n
       )) +
  geom_alluvium(aes(fill = insect_plants_cluster_name),
                width = 0, alpha = 0.5) +
  geom_stratum(width = 0.5) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 2) +
  scale_x_discrete(
    limits = c("20 x 20 m Cluster", "120 x 120 m Cluster"),
    expand = c(0.05, 0.05)
  ) +
  labs(
    x = NULL,
    y = "Number of plots",
    title = "Cluster transitions (aggregated by cluster pair)",
    fill = "20 x 20 m Cluster"
  ) +
  theme_minimal() + 
  fill_scale(append_insect_plant_palette(insect_plant_clusters)) + 
  theme(legend.position = "bottom", legend.text = element_text(size = 5)) +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))
ggsave('output/figure_2_plot_movement_between_clusters.jpg', width = 2500, height = 1000, units = 'px')
```
