---
title: "Spatial correlation"
output: html_notebook
---

```{r}
source("R/common.R", local = knitr::knit_global())
source("R/externals.R", local = knitr::knit_global())
library(spdep)
library(sf)
```

# Plots to clusters
```{r}
insect_plant_cluster_json = read_input_json(INSECT_PLANT_CLUSTERS)
bird_cluster_json = read_input_json(BIRD_CLUSTERS)

row_to_df = function(x) {
  tibble(
    cluster_id = as.integer(x$cluster_id),
    cluster_name = x$cluster_name,
    representative_plot_image = x$representative_plot_image
  )
}

insect_plant_clusters = map_dfr(insect_plant_cluster_json, row_to_df) %>% append_insect_plant_palette()
bird_clusters = map_dfr(bird_cluster_json, row_to_df) %>% append_bird_palette(insect_plant_clusters)
```

```{r}
plots_in_cluster = function(cluster_json, cluster_id) {
  idx = which(sapply(cluster_json, function(x) x$cluster_id) == cluster_id)
  if (length(idx) == 0) return(NULL)
  
  df = data.frame(plot_id = cluster_json[[idx]]['plots'])
  df$cluster_id = cluster_id
  df
}

plots_in_cluster_insect_plants = function(cluster_id) plots_in_cluster(insect_plant_cluster_json, cluster_id)
plots_in_cluster_birds = function(cluster_id) plots_in_cluster(bird_cluster_json, cluster_id)
```

```{r}
insect_plants_plots = map_dfr(0:9, plots_in_cluster_insect_plants) %>% 
  left_join(insect_plant_clusters, by = 'cluster_id') %>% 
  dplyr::select(plots, cluster_name) %>% arrange(plots) %>% 
  rename(plot_id = plots, cluster_id = cluster_name) %>%
  mutate(cluster_id = as.factor(cluster_id)) %>%
  arrange(plot_id)
insect_plants_plots
```

```{r}
bird_plots = map_dfr(0:9, plots_in_cluster_birds) %>% 
  left_join(bird_clusters, by = 'cluster_id') %>% 
  dplyr::select(plots, cluster_name) %>% 
  rename(plot_id = plots, cluster_id = cluster_name) %>%
  mutate(cluster_id = as.factor(cluster_id)) %>%
  arrange(plot_id)
bird_plots
```

# Coords of Sites
```{r}
survey_squares = st_read(EXTERNAL_SHP_SURVEY_SQUARES) %>% filter(title %in% insect_plants_plots$plot_id) %>% arrange(title)
survey_squares
```

```{r}
coords = st_coordinates(st_centroid(survey_squares))
```

# Coords to cluster
```{r}
insect_plants_plots_coords = insect_plants_plots %>% arrange(plot_id)
insect_plants_plots_coords$x = coords[,1]
insect_plants_plots_coords$y = coords[,2]
insect_plants_plots_coords
```

```{r}
bird_plots_coords = bird_plots %>% arrange(plot_id)
bird_plots_coords$x = coords[,1]
bird_plots_coords$y = coords[,2]
bird_plots_coords
```

# Nearest Neigbour and Spatial Clustering
```{r}
local_scale = 500
local_scale_subtitle = 'Nearest Neighbour within 500 m'

broad_scale = 2500
broad_scale_subtitle = 'Nearest Neighbour within 2.5 km'
```

```{r}
nb_local = dnearneigh(coords, 0, local_scale)
nb_local
```

```{r}
lw_local = nb2listw(nb_local, style = "W", zero.policy = TRUE)
lw_local
```

```{r}
nb_broad = dnearneigh(coords, 0, broad_scale)
lw_broad = nb2listw(nb_broad, style = "W")
lw_broad
```

```{r}
insect_plant_clusters_scale_fill_manual_cluster = fill_scale(insect_plant_clusters)
insect_plant_clusters_scale_colour_manual_cluster = colour_scale(insect_plant_clusters)
bird_clusters_scale_fill_manual_cluster = fill_scale(bird_clusters)
bird_clusters_scale_colour_manual_cluster = colour_scale(bird_clusters)
```

```{r}
to_results_df = function(df) {
  df %>%
  as.data.frame() %>%
  rownames_to_column("pair") %>%
  rename(
    joincount = Joincount,
    expected  = Expected,
    variance  = Variance,
    z_value   = `z-value`
  ) %>%
  mutate(
    # classify pair types
    pair_type = case_when(
      pair == "Jtot" ~ "different (all)",
      sub(":.*", "", pair) == sub(".*:", "", pair) ~ "same",
      TRUE ~ "different"
    ),
    first_pair = gsub(':.*', '', pair)
  )
}
```

```{r}
jc_20m_local = joincount.multi(insect_plants_plots$cluster_id, lw_local) %>% to_results_df()
jc_20m_local
```

```{r}
plot_spatial_correlation = function(title, subtitle, jc_local, fill_scale) {
  jc_same = jc_local %>% filter(pair_type == "same") %>% mutate(x = reorder(first_pair, z_value))

  ggplot(jc_same, aes(x = x, y = z_value, fill = x)) +
    geom_col() +
    coord_flip() +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_hline(yintercept = 1.96, linetype = "dotted") +
    geom_hline(yintercept = -1.96, linetype = "dotted") +
    labs(
      x = "Habitat (same-colour joins)",
      y = "z-value (clustering vs random)",
      title = title,
      subtitle = subtitle
    ) +
    fill_scale +
    theme_minimal() +
    theme(legend.position = 'none')
}

```

```{r}
plot_spatial_correlation('Local spatial clustering of 20 x 20 m Habitat', local_scale_subtitle, jc_20m_local, insect_plant_clusters_scale_fill_manual_cluster)
ggsave('output/figure_om_spatial_local_20m_plots.jpg')
```

```{r}
jc_20m_broad = joincount.multi(insect_plants_plots$cluster_id, lw_broad) %>% to_results_df()
jc_20m_broad
```

```{r}
plot_spatial_correlation('Broad spatial clustering of 20 x 20 m Habitat', broad_scale_subtitle, jc_20m_broad, insect_plant_clusters_scale_fill_manual_cluster)
ggsave('output/figure_om_spatial_broad_20m_plots.jpg')
```

```{r}
jc_120m_local = joincount.multi(bird_plots$cluster_id, lw_local) %>% to_results_df()
jc_120m_local
```

```{r}
plot_spatial_correlation('Local spatial clustering of 120 x 120 m Habitat', local_scale_subtitle, jc_120m_local, bird_clusters_scale_fill_manual_cluster)
ggsave('output/figure_om_spatial_local_120m_plots.jpg')
```

```{r}
jc_120m_broad = joincount.multi(bird_plots$cluster_id, lw_broad) %>% to_results_df()
jc_120m_broad
```

```{r}
plot_spatial_correlation('Broad spatial clustering of 120 x 120 m Habitat', broad_scale_subtitle, jc_120m_broad, bird_clusters_scale_fill_manual_cluster)
ggsave('output/figure_om_spatial_broad_120m_plots.jpg')
```

# Density Plots
```{r}
m60_ringroad_shape = st_read(EXTERNAL_SHP_RINGROAD)


ggplot() +
  geom_sf(data = m60_ringroad_shape, fill = NA, colour = "darkblue", linewidth = 1) +
  stat_density_2d(
    data = insect_plants_plots_coords,
    aes(
      x = x, y = y,
      fill  = cluster_id,
      alpha = after_stat(..level..),
      group = cluster_id
    ),
    geom        = "polygon",
    contour_var = "ndensity",
    bins        = 5
  ) +
  scale_alpha(range = c(0, 0.7), guide = "none") +
  coord_sf() +
  labs(
    fill  = "Habitat cluster",
    title = "Coloured density heat map of habitat clusters"
  ) +
  insect_plant_clusters_scale_fill_manual_cluster +
  theme_minimal() +
  theme(
    axis.text  = element_blank(),
    axis.title = element_blank()
  )
ggsave('output/figure_om_spatial_cluster_density_20m.jpg')
```

```{r}
ggplot() +
  geom_sf(data = m60_ringroad_shape, fill = NA, colour = "darkblue", linewidth = 1) +
  stat_density_2d(
    data = bird_plots_coords,
    aes(
      x = x, y = y,
      fill  = cluster_id,
      alpha = after_stat(..level..),
      group = cluster_id
    ),
    geom        = "polygon",
    contour_var = "ndensity",
    bins        = 5
  ) +
  scale_alpha(range = c(0, 0.7), guide = "none") +
  coord_sf() +
  labs(
    fill  = "Habitat cluster",
    title = "Coloured density heat map of habitat clusters"
  ) +
  insect_plant_clusters_scale_fill_manual_cluster +
  theme_minimal() +
  theme(
    axis.text  = element_blank(),
    axis.title = element_blank()
  )
ggsave('output/figure_om_spatial_cluster_density_120m.jpg')
```
```


